apiVersion: v1
kind: Service
metadata:
  name: uni_app-service 
  labels:
 app: uni_app  //Based on the app label the service will identify the pods with the exact label
spec:
  ports:
  - nodePort: 30500
 port: 80
 protocol: TCP
 targetPort: 80
type: NodePort
